### ISSUE TITLE
Considering this library for a project as it seems to be the only pdfjs wrapper that is properly "angular" in its implementation, but I'm a bit worried that the last commit is 2016 as I'm not really looking to take over maintenance of a library.  Is this still being maintained?

### ISSUE THREAD

**Issue by allauthors** [ArchmageInc/angular-pdfjs#13]

**Comment by CtrlShiftF11** [comment]
One of my friends is the author of this library.  It probably still works just fine, but he's not actively maintaining the library at this point.

**Comment by ArchmageInc** [comment]
When I was looking for a pdfjs wrapper, I came to the same situation and it is the reason I created this library. If there were a major situation where this library was broken, I would likely fix it, though I do not intend to add any new features. I have since stopped using this library instead converting the PDFs to images on the back-end. There is a lot more flexibility when working with images than there is a PDF.
